// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BookmarkService manages saved directory shortcuts.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function Add(name: string, path: string): $CancellablePromise<domain$0.Bookmark> {
    return $Call.ByID(2851069309, name, path);
}

export function List(): $CancellablePromise<domain$0.Bookmark[] | null> {
    return $Call.ByID(2727563082);
}

export function Remove(id: number): $CancellablePromise<void> {
    return $Call.ByID(3565576282, id);
}
