// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BookmarkService manages saved directory shortcuts.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * @param {string} name
 * @param {string} path
 * @returns {$CancellablePromise<domain$0.Bookmark>}
 */
export function Add(name, path) {
    return $Call.ByID(2851069309, name, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<domain$0.Bookmark[]>}
 */
export function List() {
    return $Call.ByID(2727563082).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function Remove(id) {
    return $Call.ByID(3565576282, id);
}

// Private type creation functions
const $$createType0 = domain$0.Bookmark.createFrom;
const $$createType1 = $Create.Array($$createType0);
