// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService manages remote connection profiles and SSH sessions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * AddProfile parses a connection string (e.g. "ssh user@host" or config alias) and saves it.
 */
export function AddProfile(spec: string): $CancellablePromise<domain$0.ConnectionProfile> {
    return $Call.ByID(2055959622, spec);
}

/**
 * AddRecentPath records a remote virtual path as recently visited.
 */
export function AddRecentPath(vpath: string): $CancellablePromise<void> {
    return $Call.ByID(2100475021, vpath);
}

/**
 * ConnectFromConfig connects using a host entry parsed from an SSH config file.
 * If save is true the host is also stored as a named connection profile (with IdentityFiles).
 */
export function ConnectFromConfig(host: domain$0.SSHConfigHost, password: string, save: boolean): $CancellablePromise<domain$0.ConnectResult> {
    return $Call.ByID(183864338, host, password, save);
}

/**
 * ConnectProfile connects using a saved profile. password may be empty (keys/agent).
 * password is also tried as a private-key passphrase.
 */
export function ConnectProfile(id: string, password: string): $CancellablePromise<domain$0.ConnectResult> {
    return $Call.ByID(1614696825, id, password);
}

/**
 * ConnectSpec connects from a free-form string (optionally saves). password may be empty.
 */
export function ConnectSpec(specStr: string, password: string, save: boolean): $CancellablePromise<domain$0.ConnectResult> {
    return $Call.ByID(3241223103, specStr, password, save);
}

/**
 * DefaultSSHConfigPaths returns the standard OpenSSH client config file paths.
 */
export function DefaultSSHConfigPaths(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2870403019);
}

/**
 * Disconnect closes the session for key or virtual path.
 */
export function Disconnect(keyOrPath: string): $CancellablePromise<void> {
    return $Call.ByID(369148480, keyOrPath);
}

/**
 * GetRecentPaths returns recently visited remote paths for a session key.
 */
export function GetRecentPaths(sessionKey: string): $CancellablePromise<domain$0.RemoteRecent[] | null> {
    return $Call.ByID(4024057771, sessionKey);
}

/**
 * ListProfiles returns saved connection profiles.
 */
export function ListProfiles(): $CancellablePromise<domain$0.ConnectionProfile[] | null> {
    return $Call.ByID(3747268220);
}

/**
 * ListSSHConfigHosts parses an SSH config file and returns its host entries.
 */
export function ListSSHConfigHosts(configPath: string): $CancellablePromise<domain$0.SSHConfigHost[] | null> {
    return $Call.ByID(1388953377, configPath);
}

/**
 * ListSessions returns live SSH sessions.
 */
export function ListSessions(): $CancellablePromise<domain$0.ActiveSession[] | null> {
    return $Call.ByID(4203296871);
}

/**
 * ParseSpec validates a connection string (for the Add dialog).
 */
export function ParseSpec(spec: string): $CancellablePromise<domain$0.ConnectionProfile> {
    return $Call.ByID(3749591554, spec);
}

/**
 * RemoveProfile deletes a saved profile by id.
 */
export function RemoveProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(4184816407, id);
}

/**
 * SetProfileDefaultWorkDir stores the preferred start path for a saved profile.
 */
export function SetProfileDefaultWorkDir(profileID: string, vpath: string): $CancellablePromise<void> {
    return $Call.ByID(1284601464, profileID, vpath);
}
