// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService manages remote connection profiles and SSH sessions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * AddProfile parses a connection string (e.g. "ssh user@host") and saves it.
 */
export function AddProfile(spec: string): $CancellablePromise<domain$0.ConnectionProfile> {
    return $Call.ByID(2055959622, spec);
}

/**
 * ConnectProfile connects using a saved profile. password may be empty (keys/agent).
 * Returns start path for the active pane.
 */
export function ConnectProfile(id: string, password: string): $CancellablePromise<domain$0.ConnectResult> {
    return $Call.ByID(1614696825, id, password);
}

/**
 * ConnectSpec connects from a free-form string (optionally saves). password may be empty.
 */
export function ConnectSpec(specStr: string, password: string, save: boolean): $CancellablePromise<domain$0.ConnectResult> {
    return $Call.ByID(3241223103, specStr, password, save);
}

/**
 * Disconnect closes the session for key or virtual path.
 */
export function Disconnect(keyOrPath: string): $CancellablePromise<void> {
    return $Call.ByID(369148480, keyOrPath);
}

/**
 * ListProfiles returns saved connection profiles.
 */
export function ListProfiles(): $CancellablePromise<domain$0.ConnectionProfile[] | null> {
    return $Call.ByID(3747268220);
}

/**
 * ListSessions returns live SSH sessions.
 */
export function ListSessions(): $CancellablePromise<domain$0.ActiveSession[] | null> {
    return $Call.ByID(4203296871);
}

/**
 * ParseSpec validates a connection string (for the Add dialog).
 */
export function ParseSpec(spec: string): $CancellablePromise<domain$0.ConnectionProfile> {
    return $Call.ByID(3749591554, spec);
}

/**
 * RemoveProfile deletes a saved profile by id.
 */
export function RemoveProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(4184816407, id);
}
