// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService exposes filesystem operations to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * Archive packs sources into destPath using format (zip, tar.gz, …).
 * password enables traditional zip encryption when format is zip.
 * jobID from NewJobID enables CancelJob; empty jobID is non-cancellable.
 */
export function Archive(jobID: string, sources: string[] | null, destPath: string, format: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(275001290, jobID, sources, destPath, format, password);
}

/**
 * ArchiveExtension returns the extension for a create format.
 */
export function ArchiveExtension(format: string): $CancellablePromise<string> {
    return $Call.ByID(3092024763, format);
}

/**
 * CancelJob cancels a long-running Archive/Extract/DirChildSizes started with NewJobID.
 */
export function CancelJob(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(2151147385, jobID);
}

export function Copy(sources: string[] | null, destDir: string): $CancellablePromise<void> {
    return $Call.ByID(3419756089, sources, destDir);
}

/**
 * CreateFile creates an empty file under parent (local only).
 */
export function CreateFile(parent: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1566414454, parent, name);
}

export function Delete(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(4015740351, paths);
}

/**
 * DirChildSizes returns recursive sizes for immediate child directories.
 * jobID from NewJobID enables CancelJob; empty jobID is non-cancellable.
 */
export function DirChildSizes(jobID: string, dir: string): $CancellablePromise<{ [_ in string]?: number } | null> {
    return $Call.ByID(4082514371, jobID, dir);
}

export function Exists(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(2431508164, path);
}

/**
 * Extract unpacks archivePath into destDir. password for protected rar/7z/zip when needed.
 * Does not finish the job — call FinishJob after multi-extract, or CancelJob.
 */
export function Extract(jobID: string, archivePath: string, destDir: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(1130524277, jobID, archivePath, destDir, password);
}

/**
 * FinishJob releases a completed job (no-op if already cancelled).
 */
export function FinishJob(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(3134074410, jobID);
}

export function GetHomeDir(): $CancellablePromise<string> {
    return $Call.ByID(3323712262);
}

/**
 * ListArchiveCreateFormats returns formats the create dialog can use.
 */
export function ListArchiveCreateFormats(): $CancellablePromise<string[] | null> {
    return $Call.ByID(494576994);
}

export function ListDir(path: string, showHidden: boolean): $CancellablePromise<domain$0.FileEntry[] | null> {
    return $Call.ByID(299481683, path, showHidden);
}

export function ListPathCompletions(partial: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1004009986, partial);
}

export function Mkdir(parent: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1882308327, parent, name);
}

export function Move(sources: string[] | null, destDir: string): $CancellablePromise<void> {
    return $Call.ByID(113183649, sources, destDir);
}

/**
 * NewJobID allocates a cancellable job context and returns its id.
 */
export function NewJobID(): $CancellablePromise<string> {
    return $Call.ByID(1905051552);
}

/**
 * Open opens a path with the OS default application.
 */
export function Open(path: string): $CancellablePromise<void> {
    return $Call.ByID(2881462676, path);
}

/**
 * ReadTextFile reads a local text file for the built-in editor.
 */
export function ReadTextFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(2975228065, path);
}

export function Rename(oldPath: string, newName: string): $CancellablePromise<string> {
    return $Call.ByID(2594677718, oldPath, newName);
}

/**
 * SearchTree finds nested files/folders under root (local only; Go-to).
 */
export function SearchTree(root: string, query: string, showHidden: boolean, limit: number): $CancellablePromise<domain$0.SearchHit[] | null> {
    return $Call.ByID(3279656272, root, query, showHidden, limit);
}

/**
 * WriteTextFile writes a local text file from the built-in editor.
 */
export function WriteTextFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1752048786, path, content);
}
