// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService exposes filesystem operations to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * @param {string[]} sources
 * @param {string} destDir
 * @returns {$CancellablePromise<void>}
 */
export function Copy(sources, destDir) {
    return $Call.ByID(3419756089, sources, destDir);
}

/**
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function Delete(paths) {
    return $Call.ByID(4015740351, paths);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function Exists(path) {
    return $Call.ByID(2431508164, path);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetHomeDir() {
    return $Call.ByID(3323712262);
}

/**
 * @param {string} path
 * @param {boolean} showHidden
 * @returns {$CancellablePromise<domain$0.FileEntry[]>}
 */
export function ListDir(path, showHidden) {
    return $Call.ByID(299481683, path, showHidden).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} partial
 * @returns {$CancellablePromise<string[]>}
 */
export function ListPathCompletions(partial) {
    return $Call.ByID(1004009986, partial).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} parent
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Mkdir(parent, name) {
    return $Call.ByID(1882308327, parent, name);
}

/**
 * @param {string[]} sources
 * @param {string} destDir
 * @returns {$CancellablePromise<void>}
 */
export function Move(sources, destDir) {
    return $Call.ByID(113183649, sources, destDir);
}

/**
 * @param {string} oldPath
 * @param {string} newName
 * @returns {$CancellablePromise<string>}
 */
export function Rename(oldPath, newName) {
    return $Call.ByID(2594677718, oldPath, newName);
}

// Private type creation functions
const $$createType0 = domain$0.FileEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
