// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService exposes filesystem operations to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function Copy(sources: string[] | null, destDir: string): $CancellablePromise<void> {
    return $Call.ByID(3419756089, sources, destDir);
}

export function Delete(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(4015740351, paths);
}

export function Exists(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(2431508164, path);
}

export function GetHomeDir(): $CancellablePromise<string> {
    return $Call.ByID(3323712262);
}

export function ListDir(path: string): $CancellablePromise<domain$0.FileEntry[] | null> {
    return $Call.ByID(299481683, path);
}

export function Mkdir(parent: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1882308327, parent, name);
}

export function Move(sources: string[] | null, destDir: string): $CancellablePromise<void> {
    return $Call.ByID(113183649, sources, destDir);
}

export function Rename(oldPath: string, newName: string): $CancellablePromise<string> {
    return $Call.ByID(2594677718, oldPath, newName);
}
