// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService exposes cheap, cached git working-tree status for the file list.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * FileDiff returns HEAD vs working-tree text for a local file (for the built-in diff viewer).
 * Soft-fails with Message set; remote paths return an empty result.
 */
export function FileDiff(path: string): $CancellablePromise<domain$0.GitFileDiff> {
    return $Call.ByID(1612400113, path);
}

/**
 * StatusForDir returns git status for immediate children of path.
 * Remote paths and non-repos return an empty result (no error).
 */
export function StatusForDir(path: string): $CancellablePromise<domain$0.GitDirStatus> {
    return $Call.ByID(4286462636, path);
}
