// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PortService lists local TCP listeners and force-kills processes by PID.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function Kill(pid: number): $CancellablePromise<void> {
    return $Call.ByID(2795784817, pid);
}

export function KillAll(pids: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(640493832, pids);
}

export function List(): $CancellablePromise<domain$0.PortListener[] | null> {
    return $Call.ByID(3736556441);
}

export function ListProcesses(): $CancellablePromise<domain$0.ProcessInfo[] | null> {
    return $Call.ByID(3484333438);
}
