// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService persists app settings and shortcuts in encrypted SQLite (app.db).
 * Legacy settings.json / shortcuts.json are migrated once on first load.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function GetConfigDir(): $CancellablePromise<string> {
    return $Call.ByID(780043014);
}

export function GetPanePaths(): $CancellablePromise<domain$0.PanePaths> {
    return $Call.ByID(4161505117);
}

export function GetSettings(): $CancellablePromise<domain$0.Settings> {
    return $Call.ByID(1459755560);
}

export function GetSettingsPath(): $CancellablePromise<string> {
    return $Call.ByID(288106751);
}

export function GetShortcuts(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(3475743136);
}

export function GetShortcutsPath(): $CancellablePromise<string> {
    return $Call.ByID(378564007);
}

export function ListShortcutDefs(): $CancellablePromise<domain$0.ShortcutDef[] | null> {
    return $Call.ByID(4040094097);
}

export function OpenInOS(path: string): $CancellablePromise<void> {
    return $Call.ByID(4147658382, path);
}

export function RevealInOS(path: string): $CancellablePromise<void> {
    return $Call.ByID(1818025483, path);
}

export function SavePanePaths(left: string, right: string): $CancellablePromise<void> {
    return $Call.ByID(2575467756, left, right);
}

export function SaveSettings(settings: domain$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(2524387571, settings);
}

export function SaveShortcuts(shortcuts: { [_ in string]?: string } | null): $CancellablePromise<void> {
    return $Call.ByID(695437449, shortcuts);
}
