// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService persists app settings and shortcuts in encrypted SQLite (app.db).
 * Legacy settings.json / shortcuts.json are migrated once on first load.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * AddSearchHistory records a non-empty value for field (query|replace|include|exclude).
 */
export function AddSearchHistory(field: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3012693094, field, value);
}

export function GetConfigDir(): $CancellablePromise<string> {
    return $Call.ByID(780043014);
}

/**
 * GetGridPrefs returns each pane's file-grid sort, visibility, and column order.
 * Missing or invalid blobs yield defaults (Name/asc, nothing hidden, empty order).
 */
export function GetGridPrefs(): $CancellablePromise<domain$0.GridPrefs> {
    return $Call.ByID(449688525);
}

/**
 * GetPaneTabs returns each pane's saved tab list. If no tabs blob was ever
 * saved, or a pane's list ended up empty, it falls back to a single tab
 * derived from the legacy Settings.LeftPath/RightPath so existing installs
 * (and e2e's settings.json seed) keep working.
 */
export function GetPaneTabs(): $CancellablePromise<domain$0.PaneTabs> {
    return $Call.ByID(1411864435);
}

/**
 * GetSearchPrefs returns last Find-in-files dialog fields.
 */
export function GetSearchPrefs(): $CancellablePromise<domain$0.SearchPrefs> {
    return $Call.ByID(2690969973);
}

export function GetSettings(): $CancellablePromise<domain$0.Settings> {
    return $Call.ByID(1459755560);
}

export function GetSettingsPath(): $CancellablePromise<string> {
    return $Call.ByID(288106751);
}

export function GetShortcuts(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(3475743136);
}

export function GetShortcutsPath(): $CancellablePromise<string> {
    return $Call.ByID(378564007);
}

/**
 * ListSearchHistory returns newest-first history for field (max 500).
 */
export function ListSearchHistory(field: string, limit: number): $CancellablePromise<string[] | null> {
    return $Call.ByID(151217717, field, limit);
}

export function ListShortcutDefs(): $CancellablePromise<domain$0.ShortcutDef[] | null> {
    return $Call.ByID(4040094097);
}

export function OpenInOS(path: string): $CancellablePromise<void> {
    return $Call.ByID(4147658382, path);
}

export function RevealInOS(path: string): $CancellablePromise<void> {
    return $Call.ByID(1818025483, path);
}

/**
 * SaveGridPrefs persists each pane's file-grid preferences.
 */
export function SaveGridPrefs(prefs: domain$0.GridPrefs): $CancellablePromise<void> {
    return $Call.ByID(796512464, prefs);
}

/**
 * SavePaneTabs persists each pane's tab list and mirrors the active tab's
 * path into Settings.LeftPath/RightPath, which stays the boot fallback.
 */
export function SavePaneTabs(tabs: domain$0.PaneTabs): $CancellablePromise<void> {
    return $Call.ByID(4028892756, tabs);
}

/**
 * SaveSearchPrefs persists Find-in-files dialog fields.
 */
export function SaveSearchPrefs(prefs: domain$0.SearchPrefs): $CancellablePromise<void> {
    return $Call.ByID(3692396904, prefs);
}

export function SaveSettings(settings: domain$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(2524387571, settings);
}

export function SaveShortcuts(shortcuts: { [_ in string]?: string } | null): $CancellablePromise<void> {
    return $Call.ByID(695437449, shortcuts);
}
