// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService persists app settings (paths, theme).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function Get(key: string): $CancellablePromise<string> {
    return $Call.ByID(1929760965, key);
}

export function GetAll(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(900387940);
}

export function GetPanePaths(): $CancellablePromise<domain$0.PanePaths> {
    return $Call.ByID(4161505117);
}

export function GetTheme(): $CancellablePromise<string> {
    return $Call.ByID(2239124882);
}

export function SavePanePaths(left: string, right: string): $CancellablePromise<void> {
    return $Call.ByID(2575467756, left, right);
}

export function Set(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2349688505, key, value);
}

export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(53978750, theme);
}
