// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService persists app settings and shortcuts as JSON files.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigDir() {
    return $Call.ByID(780043014);
}

/**
 * @returns {$CancellablePromise<domain$0.PanePaths>}
 */
export function GetPanePaths() {
    return $Call.ByID(4161505117).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<domain$0.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(1459755560).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetSettingsPath() {
    return $Call.ByID(288106751);
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetShortcuts() {
    return $Call.ByID(3475743136).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetShortcutsPath() {
    return $Call.ByID(378564007);
}

/**
 * @returns {$CancellablePromise<domain$0.ShortcutDef[]>}
 */
export function ListShortcutDefs() {
    return $Call.ByID(4040094097).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenInOS(path) {
    return $Call.ByID(4147658382, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RevealInOS(path) {
    return $Call.ByID(1818025483, path);
}

/**
 * @param {string} left
 * @param {string} right
 * @returns {$CancellablePromise<void>}
 */
export function SavePanePaths(left, right) {
    return $Call.ByID(2575467756, left, right);
}

/**
 * @param {domain$0.Settings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(2524387571, settings);
}

/**
 * @param {{ [_ in string]?: string }} shortcuts
 * @returns {$CancellablePromise<void>}
 */
export function SaveShortcuts(shortcuts) {
    return $Call.ByID(695437449, shortcuts);
}

// Private type creation functions
const $$createType0 = domain$0.PanePaths.createFrom;
const $$createType1 = domain$0.Settings.createFrom;
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = domain$0.ShortcutDef.createFrom;
const $$createType4 = $Create.Array($$createType3);
