// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService manages interactive shell sessions per pane (left/right),
 * local via PTY or remote via SSH.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * IsRunning reports whether a session exists for the pane.
 */
export function IsRunning(paneID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2732088041, paneID);
}

/**
 * Resize updates the pane's terminal size.
 */
export function Resize(paneID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(3439050986, paneID, cols, rows);
}

/**
 * SetApp injects the application for event emission (call after application.New).
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(850735781, app);
}

/**
 * SetCwd sends cd to the running shell when the pane path changes.
 */
export function SetCwd(paneID: string, cwd: string): $CancellablePromise<void> {
    return $Call.ByID(1023067116, paneID, cwd);
}

/**
 * Start spawns a shell at cwd for the given pane: a local login shell, or an
 * SSH shell when cwd is an ssh:// virtual path.
 */
export function Start(paneID: string, cwd: string): $CancellablePromise<void> {
    return $Call.ByID(2443104662, paneID, cwd);
}

/**
 * Stop kills the pane's shell session.
 */
export function Stop(paneID: string): $CancellablePromise<void> {
    return $Call.ByID(845114430, paneID);
}

/**
 * Write sends data to the pane's shell stdin.
 */
export function Write(paneID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(4079804177, paneID, data);
}
