// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService is a thin Wails-bound façade over app.Updater.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * CheckAndInstall opens the Wails update window, checks GitHub Releases, and
 * if a newer version is found, downloads/verifies/stages it for Restart & Apply.
 * Errors propagate to the frontend so the caller can show failures.
 */
export function CheckAndInstall(): $CancellablePromise<void> {
    return $Call.ByID(3005346729);
}

/**
 * GetVersion returns the build-injected app version (no leading v).
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(4232056307);
}

/**
 * OpenReleasesPage opens the GitHub releases page in the browser.
 */
export function OpenReleasesPage(): $CancellablePromise<void> {
    return $Call.ByID(2403015818);
}

/**
 * ReleasesURL is the human-facing releases page.
 */
export function ReleasesURL(): $CancellablePromise<string> {
    return $Call.ByID(1370296590);
}
