// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService checks GitHub Releases and downloads update packages.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * ApplyUpdate opens the downloaded package with the OS (installer / DMG / folder).
 */
export function ApplyUpdate(localPath: string): $CancellablePromise<void> {
    return $Call.ByID(687415104, localPath);
}

/**
 * CheckForUpdate compares the local version to the latest GitHub release.
 */
export function CheckForUpdate(): $CancellablePromise<domain$0.UpdateInfo> {
    return $Call.ByID(156204997);
}

/**
 * DownloadUpdate saves the asset URL to a temp file and returns its path.
 */
export function DownloadUpdate(assetURL: string): $CancellablePromise<string> {
    return $Call.ByID(3687934394, assetURL);
}

/**
 * GetVersion returns the build-injected app version (no leading v).
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(4232056307);
}

/**
 * OpenReleasesPage opens the GitHub releases page in the browser.
 */
export function OpenReleasesPage(): $CancellablePromise<void> {
    return $Call.ByID(2403015818);
}

/**
 * ReleasesURL is the human-facing releases page.
 */
export function ReleasesURL(): $CancellablePromise<string> {
    return $Call.ByID(1370296590);
}
