// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Bookmark,
    FileEntry,
    PanePaths,
    Settings,
    ShortcutDef
} from "./models.js";
