// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Bookmark is a saved directory shortcut.
 */
export class Bookmark {
    /**
     * Creates a new Bookmark instance.
     * @param {Partial<Bookmark>} [$$source = {}] - The source object to create the Bookmark.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("sortOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Bookmark instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Bookmark}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Bookmark(/** @type {Partial<Bookmark>} */($$parsedSource));
    }
}

/**
 * FileEntry is a single directory listing row.
 */
export class FileEntry {
    /**
     * Creates a new FileEntry instance.
     * @param {Partial<FileEntry>} [$$source = {}] - The source object to create the FileEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            /**
             * unix milliseconds
             * @member
             * @type {number}
             */
            this["modTime"] = 0;
        }
        if (!("ext" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ext"] = "";
        }
        if (!("isSymlink" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isSymlink"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry(/** @type {Partial<FileEntry>} */($$parsedSource));
    }
}

/**
 * PanePaths holds last-used left/right directory paths.
 */
export class PanePaths {
    /**
     * Creates a new PanePaths instance.
     * @param {Partial<PanePaths>} [$$source = {}] - The source object to create the PanePaths.
     */
    constructor($$source = {}) {
        if (!("left" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["left"] = "";
        }
        if (!("right" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["right"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PanePaths instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PanePaths}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PanePaths(/** @type {Partial<PanePaths>} */($$parsedSource));
    }
}

/**
 * Settings is the contents of settings.json.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("showHidden" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showHidden"] = false;
        }
        if (!("showExtensions" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showExtensions"] = false;
        }
        if (!("leftPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["leftPath"] = "";
        }
        if (!("rightPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rightPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * ShortcutDef describes one bindable action (for UI + docs).
 */
export class ShortcutDef {
    /**
     * Creates a new ShortcutDef instance.
     * @param {Partial<ShortcutDef>} [$$source = {}] - The source object to create the ShortcutDef.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("binding" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["binding"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShortcutDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShortcutDef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShortcutDef(/** @type {Partial<ShortcutDef>} */($$parsedSource));
    }
}
