// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIUsage is one AI coding agent's quota snapshot.
 */
export interface AIUsage {
    /**
     * claude | grok | cursor
     */
    "id": string;
    "name": string;

    /**
     * ok | not-installed | unsupported | error
     */
    "status": string;
    "error"?: string;

    /**
     * derived locally, not authoritative
     */
    "estimate": boolean;
    "limits": AIUsageLimit[] | null;
    "details": AIUsageDetail[] | null;
}

/**
 * AIUsageDetail is one free-form expanded line (e.g. request counts).
 */
export interface AIUsageDetail {
    "label": string;
    "value": string;

    /**
     * 0 = header, 1 = indented bullet
     */
    "depth": number;
}

/**
 * AIUsageLimit is one quota window (e.g. "current session").
 */
export interface AIUsageLimit {
    "label": string;

    /**
     * 0..100, -1 = unknown
     */
    "percent": number;
    "resetAt"?: string;
}

/**
 * ActiveSession is a live remote connection for UI.
 */
export interface ActiveSession {
    /**
     * user@host:port
     */
    "key": string;
    "protocol": string;
    "user": string;
    "host": string;
    "port": number;

    /**
     * ssh://user@host:port/
     */
    "rootPath": string;
}

/**
 * Bookmark is a saved directory shortcut.
 */
export interface Bookmark {
    "id": number;
    "name": string;
    "path": string;
    "sortOrder": number;
    "createdAt": string;
}

/**
 * ConnectResult is returned after a successful SSH dial.
 */
export interface ConnectResult {
    "rootPath": string;

    /**
     * remote home or root
     */
    "homePath": string;

    /**
     * session key user@host:port
     */
    "key": string;

    /**
     * saved profile id when known
     */
    "profileId"?: string;

    /**
     * profile default start path if set
     */
    "defaultWorkDir"?: string;

    /**
     * SMB share list after connect
     */
    "shares"?: SMBShare[] | null;

    /**
     * OS/Finder mounted; paths are local
     */
    "localMount"?: boolean;
}

/**
 * ConnectionProfile is a saved remote connection (SSH or SMB).
 */
export interface ConnectionProfile {
    "id": string;

    /**
     * "ssh" or "smb"
     */
    "protocol": string;
    "user": string;
    "host": string;
    "port": number;

    /**
     * display name; default user@host
     */
    "label": string;

    /**
     * ~/.ssh/config Host alias (re-resolved on connect)
     */
    "configAlias"?: string;

    /**
     * private key paths (also re-merged from config)
     */
    "identityFiles"?: string[] | null;

    /**
     * preferred start path
     */
    "defaultWorkDir"?: string;

    /**
     * SMB NTLM domain
     */
    "domain"?: string;
}

/**
 * DirSizes is the result of a recursive child-size calculation. Denied lists the
 * child directories the walk could not fully read, so the UI can mark them
 * rather than silently reporting an undercount.
 */
export interface DirSizes {
    "sizes": { [_ in string]?: number } | null;
    "denied": string[] | null;
}

/**
 * DiskUsage is capacity of the volume that contains Path.
 */
export interface DiskUsage {
    "path": string;
    "total": number;

    /**
     * available to the user (bavail)
     */
    "free": number;
    "used": number;
}

/**
 * FileEntry is a single directory listing row.
 */
export interface FileEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;

    /**
     * unix milliseconds
     */
    "modTime": number;
    "ext": string;
    "isSymlink": boolean;

    /**
     * Access is "full" | "readonly" | "partial" | "none", or "" when unknown.
     * Remote (SFTP) entries are always "": Windows OpenSSH reports a constant
     * mode for everything, so the bits would be a lie. Remote access is instead
     * discovered by operations that actually get denied — see DirSizes.Denied.
     */
    "access": string;
}

/**
 * GitDirStatus is git status for immediate children of one listed directory.
 */
export interface GitDirStatus {
    /**
     * empty if not in a repo
     */
    "repoRoot": string;
    "entries": GitStatusEntry[] | null;
}

/**
 * GitFileDiff is HEAD vs working-tree content for one local file (read-only viewer).
 */
export interface GitFileDiff {
    "path": string;
    "repoRoot": string;
    "relPath": string;

    /**
     * M|A|D|U|? or empty
     */
    "status": string;
    "oldText": string;
    "newText": string;
    "binary": boolean;
    "truncated": boolean;

    /**
     * soft-fail reason when no usable content
     */
    "message": string;
}

/**
 * GitStatusEntry is one child name with a compact git working-tree status.
 * Status is one of: M (modified), A (added), D (deleted), U (unmerged), ? (untracked).
 */
export interface GitStatusEntry {
    "name": string;
    "status": string;
}

/**
 * GridPrefs holds independent left/right file-grid column preferences.
 */
export interface GridPrefs {
    "left": PaneGridPrefs;
    "right": PaneGridPrefs;
}

/**
 * OpenWithApp is one OS application that can open a local file.
 */
export interface OpenWithApp {
    /**
     * bundle path, .desktop id, or executable
     */
    "id": string;
    "name": string;
}

/**
 * PaneGridPrefs is one pane's file-grid sort, hidden columns, and column order.
 */
export interface PaneGridPrefs {
    /**
     * default "displayName"
     */
    "sortField": string;

    /**
     * "asc" | "desc"
     */
    "sortDir": string;

    /**
     * fields hidden; icon+displayName cannot hide
     */
    "hidden": string[] | null;

    /**
     * fields left-to-right; unknown fields appended
     */
    "order": string[] | null;
}

/**
 * PaneTabs holds each pane's open tabs and which one is active.
 */
export interface PaneTabs {
    "left": TabState[] | null;
    "leftActive": number;
    "right": TabState[] | null;
    "rightActive": number;
}

/**
 * PortListener is a local TCP socket in LISTEN state.
 */
export interface PortListener {
    "port": number;
    "pid": number;
    "process": string;

    /**
     * "tcp"
     */
    "proto": string;
}

/**
 * RemoteRecent is a recently visited remote directory path.
 */
export interface RemoteRecent {
    "sessionKey": string;

    /**
     * ssh:// virtual path
     */
    "path": string;

    /**
     * remote abs path for display
     */
    "label": string;

    /**
     * RFC3339
     */
    "lastVisited": string;
}

/**
 * ReplaceAllResult summarizes a batch replace.
 */
export interface ReplaceAllResult {
    "filesChanged": number;
    "replacements": number;
}

/**
 * SMBShare is one share exported by an SMB host.
 */
export interface SMBShare {
    "name": string;
    "hidden": boolean;

    /**
     * set when the OS mounted the volume
     */
    "localPath"?: string;
}

/**
 * SSHConfigHost is a host entry from an OpenSSH client config file.
 */
export interface SSHConfigHost {
    "alias": string;
    "hostName": string;
    "user": string;
    "port": number;
    "identityFiles": string[] | null;

    /**
     * absolute path of the file this entry was read from
     */
    "configPath"?: string;
}

/**
 * SearchHit is one result from nested file/folder search (Go-to).
 */
export interface SearchHit {
    "name": string;
    "path": string;
    "isDir": boolean;
    "relPath": string;
}

/**
 * SearchPrefs is the last Find-in-files dialog state (persisted).
 */
export interface SearchPrefs {
    "query": string;
    "replace": string;
    "include": string;
    "exclude": string;

    /**
     * content | folders
     */
    "mode": string;
    "replaceOpen": boolean;
    "caseSensitive": boolean;
}

/**
 * Settings is the contents of settings.json.
 */
export interface Settings {
    "theme": string;
    "showHidden": boolean;
    "showExtensions": boolean;
    "showGitStatus": boolean;
    "useBuiltInEditor": boolean;
    "autoCheckUpdates": boolean;
    "updateCheckIntervalDays": number;

    /**
     * RFC3339; empty if never
     */
    "lastUpdateCheckAt": string;

    /**
     * remote version user skipped
     */
    "skippedUpdateVersion": string;
    "leftPath": string;
    "rightPath": string;
}

/**
 * ShortcutDef describes one bindable action (for UI + docs).
 */
export interface ShortcutDef {
    "id": string;
    "label": string;
    "description": string;
    "binding": string;
}

/**
 * TabState is one open tab in a pane (path only; history is not persisted).
 */
export interface TabState {
    "path": string;
}

/**
 * Volume is an OS-mounted drive, network share, or disk image.
 */
export interface Volume {
    "path": string;
    "name": string;

    /**
     * internal | external | network | disk-image
     */
    "kind": string;
    "unmountable": boolean;

    /**
     * .dmg path when known
     */
    "sourcePath"?: string;
    "device"?: string;
}

/**
 * WindowState is the last used main-window size (persisted separately from Settings).
 */
export interface WindowState {
    "width": number;
    "height": number;
}
