// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActiveSession is a live remote connection for UI.
 */
export interface ActiveSession {
    /**
     * user@host:port
     */
    "key": string;
    "protocol": string;
    "user": string;
    "host": string;
    "port": number;

    /**
     * ssh://user@host:port/
     */
    "rootPath": string;
}

/**
 * Bookmark is a saved directory shortcut.
 */
export interface Bookmark {
    "id": number;
    "name": string;
    "path": string;
    "sortOrder": number;
    "createdAt": string;
}

/**
 * ConnectResult is returned after a successful SSH dial.
 */
export interface ConnectResult {
    "rootPath": string;

    /**
     * preferred start path (remote home or root)
     */
    "homePath": string;
    "key": string;
}

/**
 * ConnectionProfile is a saved remote connection (SSH now; FTP/SFTP later).
 */
export interface ConnectionProfile {
    "id": string;

    /**
     * "ssh", future: "ftp", "sftp"
     */
    "protocol": string;
    "user": string;
    "host": string;
    "port": number;

    /**
     * display name; default user@host
     */
    "label": string;
}

/**
 * FileEntry is a single directory listing row.
 */
export interface FileEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;

    /**
     * unix milliseconds
     */
    "modTime": number;
    "ext": string;
    "isSymlink": boolean;
}

/**
 * PanePaths holds last-used left/right directory paths.
 */
export interface PanePaths {
    "left": string;
    "right": string;
}

/**
 * Settings is the contents of settings.json.
 */
export interface Settings {
    "theme": string;
    "showHidden": boolean;
    "showExtensions": boolean;
    "leftPath": string;
    "rightPath": string;
}

/**
 * ShortcutDef describes one bindable action (for UI + docs).
 */
export interface ShortcutDef {
    "id": string;
    "label": string;
    "description": string;
    "binding": string;
}
