// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActiveSession is a live remote connection for UI.
 */
export interface ActiveSession {
    /**
     * user@host:port
     */
    "key": string;
    "protocol": string;
    "user": string;
    "host": string;
    "port": number;

    /**
     * ssh://user@host:port/
     */
    "rootPath": string;
}

/**
 * Bookmark is a saved directory shortcut.
 */
export interface Bookmark {
    "id": number;
    "name": string;
    "path": string;
    "sortOrder": number;
    "createdAt": string;
}

/**
 * ConnectResult is returned after a successful SSH dial.
 */
export interface ConnectResult {
    "rootPath": string;

    /**
     * remote home or root
     */
    "homePath": string;

    /**
     * session key user@host:port
     */
    "key": string;

    /**
     * saved profile id when known
     */
    "profileId"?: string;

    /**
     * profile default start path if set
     */
    "defaultWorkDir"?: string;
}

/**
 * ConnectionProfile is a saved remote connection (SSH now; FTP/SFTP later).
 */
export interface ConnectionProfile {
    "id": string;

    /**
     * "ssh", future: "ftp", "sftp"
     */
    "protocol": string;
    "user": string;
    "host": string;
    "port": number;

    /**
     * display name; default user@host
     */
    "label": string;

    /**
     * ~/.ssh/config Host alias (re-resolved on connect)
     */
    "configAlias"?: string;

    /**
     * private key paths (also re-merged from config)
     */
    "identityFiles"?: string[] | null;

    /**
     * preferred ssh:// start path
     */
    "defaultWorkDir"?: string;
}

/**
 * FileEntry is a single directory listing row.
 */
export interface FileEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;

    /**
     * unix milliseconds
     */
    "modTime": number;
    "ext": string;
    "isSymlink": boolean;
}

/**
 * GitDirStatus is git status for immediate children of one listed directory.
 */
export interface GitDirStatus {
    /**
     * empty if not in a repo
     */
    "repoRoot": string;
    "entries": GitStatusEntry[] | null;
}

/**
 * GitFileDiff is HEAD vs working-tree content for one local file (read-only viewer).
 */
export interface GitFileDiff {
    "path": string;
    "repoRoot": string;
    "relPath": string;

    /**
     * M|A|D|U|? or empty
     */
    "status": string;
    "oldText": string;
    "newText": string;
    "binary": boolean;
    "truncated": boolean;

    /**
     * soft-fail reason when no usable content
     */
    "message": string;
}

/**
 * GitStatusEntry is one child name with a compact git working-tree status.
 * Status is one of: M (modified), A (added), D (deleted), U (unmerged), ? (untracked).
 */
export interface GitStatusEntry {
    "name": string;
    "status": string;
}

/**
 * PaneTabs holds each pane's open tabs and which one is active.
 */
export interface PaneTabs {
    "left": TabState[] | null;
    "leftActive": number;
    "right": TabState[] | null;
    "rightActive": number;
}

/**
 * RemoteRecent is a recently visited remote directory path.
 */
export interface RemoteRecent {
    "sessionKey": string;

    /**
     * ssh:// virtual path
     */
    "path": string;

    /**
     * remote abs path for display
     */
    "label": string;

    /**
     * RFC3339
     */
    "lastVisited": string;
}

/**
 * ReplaceAllResult summarizes a batch replace.
 */
export interface ReplaceAllResult {
    "filesChanged": number;
    "replacements": number;
}

/**
 * SSHConfigHost is a host entry from an OpenSSH client config file.
 */
export interface SSHConfigHost {
    "alias": string;
    "hostName": string;
    "user": string;
    "port": number;
    "identityFiles": string[] | null;
}

/**
 * SearchHit is one result from nested file/folder search (Go-to).
 */
export interface SearchHit {
    "name": string;
    "path": string;
    "isDir": boolean;
    "relPath": string;
}

/**
 * SearchPrefs is the last Find-in-files dialog state (persisted).
 */
export interface SearchPrefs {
    "query": string;
    "replace": string;
    "include": string;
    "exclude": string;

    /**
     * content | folders
     */
    "mode": string;
    "replaceOpen": boolean;
    "caseSensitive": boolean;
}

/**
 * Settings is the contents of settings.json.
 */
export interface Settings {
    "theme": string;
    "showHidden": boolean;
    "showExtensions": boolean;
    "showGitStatus": boolean;
    "useBuiltInEditor": boolean;
    "autoCheckUpdates": boolean;
    "updateCheckIntervalDays": number;

    /**
     * RFC3339; empty if never
     */
    "lastUpdateCheckAt": string;

    /**
     * remote version user skipped
     */
    "skippedUpdateVersion": string;
    "leftPath": string;
    "rightPath": string;
}

/**
 * ShortcutDef describes one bindable action (for UI + docs).
 */
export interface ShortcutDef {
    "id": string;
    "label": string;
    "description": string;
    "binding": string;
}

/**
 * TabState is one open tab in a pane (path only; history is not persisted).
 */
export interface TabState {
    "path": string;
}
